### ISSUE TITLE
LED Matrix P2 64x64 Arduino Uno

### ISSUE THREAD

**Issue by Jonas-Hofmann-2020** [CamelCaseName/HUB75Enano#1]
Hey,

does the code also work with P2 64x64 LED Matrix and Arduino Uno?

Thanks

**Comment by CamelCaseName** [comment]
Hi, 

this library is not done yet, but it will then only work with Panels using the ICND2153 or clone as a LED driver, and using an SM5368 or compatible LED row driver. it is super purpose built for that type of panel. Also technically the name is kind of wrong, as those chips don't use the "standard" HUB75 protocol. It should work with the arduino uno though, as i develop it on a nano. But you'll probably need a different panel :(

**Comment by CamelCaseName** [comment]
stale
